[tool.poetry]
name = "arisc.how"
version = "0.1.0"
description = ""
authors = ["Aris Chow <arischow@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.1.2"
markdown-it-py = {extras = ["plugins"], version = "^2.1.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
