name: Publish
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update && sudo apt-get install -y make && pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: poetry install
      - run: npm ci
      - run: make build
      - uses: actions/upload-artifact@v3
        with:
          name: site-data
          path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-22.04
    environment: live
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: site-data
          path: ./
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "./dist/*"
          target: ${{ secrets.SERVER_TARGET }}
